# Generated by Django 4.2.4 on 2023-08-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Student ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last Name"),
                ),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("contact", models.CharField(max_length=100, verbose_name="Contact")),
                ("address", models.CharField(max_length=300, verbose_name="Address")),
                (
                    "type",
                    models.CharField(
                        choices=[("U", "Undergraduate"), ("P", "Postgraduate")],
                        max_length=30,
                        verbose_name="Student Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
    ]
