# Generated by Django 4.2.6 on 2023-10-07 04:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCard",
            fields=[
                (
                    "card_num",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Card Number"
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(auto_now_add=True, verbose_name="Issued on"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        default=datetime.date(2024, 10, 6), verbose_name="Expires on"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User ID",
                    ),
                ),
            ],
        ),
    ]
