# Generated by Django 4.2.6 on 2023-10-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members_card", "0002_membercard_active_alter_membercard_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercard",
            name="photo",
            field=models.URLField(blank=True, verbose_name="User Image"),
        ),
    ]
