# Generated by Django 4.2.6 on 2023-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members_card", "0006_alter_membercard_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membercard",
            name="photo",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="User Image"
            ),
        ),
    ]
