# Generated by Django 4.2.6 on 2023-10-19 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members_card", "0009_alter_membercard_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membercard",
            name="expiry_date",
            field=models.DateField(
                default=datetime.date(2024, 10, 18), verbose_name="Expires on"
            ),
        ),
    ]
