# Generated by Django 4.2.4 on 2023-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last Name"),
                ),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("contact", models.CharField(max_length=100, verbose_name="Contact")),
                ("address", models.CharField(max_length=300, verbose_name="Address")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("U", "Undergraduate"),
                            ("P", "Postgraduate"),
                            ("S", "Staff"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Is active")),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
