# Generated by Django 4.2.4 on 2023-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_contact_user_gender_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=6,
                verbose_name="Gender",
            ),
        ),
    ]
