# Generated by Django 4.2.4 on 2023-09-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=6,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Last Name"),
        ),
    ]
